# Generated by Django 2.2.1 on 2019-05-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=70)),
                ('user_name', models.CharField(max_length=55)),
                ('profile_pic', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_nr', models.CharField(max_length=4)),
                ('ledger', models.CharField(max_length=2)),
                ('account_number', models.CharField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
    ]
