# Generated by Django 2.2.1 on 2019-05-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userbankinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
