# Generated by Django 2.2.1 on 2019-05-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('street_nr', models.CharField(blank=True, max_length=10)),
                ('price', models.SmallIntegerField()),
                ('on_sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PostalCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='OnHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=None)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='profiles.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='profiles.User')),
            ],
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=999)),
                ('rooms', models.SmallIntegerField()),
                ('size', models.CharField(max_length=200)),
                ('garage', models.BooleanField(default=False)),
                ('extra_apartment', models.BooleanField(default=False)),
                ('new_building', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('entrance', models.BooleanField(default=False)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.HouseType')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='p_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.PostalCodes'),
        ),
        migrations.AddField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.User')),
            ],
        ),
    ]
