# Generated by Django 2.2.1 on 2019-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
