# Generated by Django 2.2.1 on 2019-05-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='houseimages',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='houseinfo',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='onhold',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='house_id',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
