# Generated by Django 2.2.1 on 2019-05-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190506_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseImages',
            new_name='HouseImage',
        ),
    ]
