# Generated by Django 2.2.1 on 2019-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_sellingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='buildyear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
