# Generated by Django 2.2.1 on 2019-05-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190508_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='size',
            field=models.SmallIntegerField(),
        ),
    ]
