# Generated by Django 2.2.1 on 2019-05-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20190513_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House'),
        ),
    ]
