# Generated by Django 2.2.1 on 2019-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190513_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
