# Generated by Django 2.2.1 on 2019-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_offers_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
