# Generated by Django 2.2.1 on 2019-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20190516_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
